import type { Metadata } from "next";
import { Be_Vietnam_Pro, Unbounded } from "next/font/google";
import "./globals.css";
import MobileNavigationWrapper from "@/components/layout/MobileNavigationWrapper";

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Conflict Wire - Breaking News on Global Conflicts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietnamPro.variable} ${unbounded.variable} font-sans antialiased`}
      >
        <MobileNavigationWrapper>
          {children}
        </MobileNavigationWrapper>
      </body>
    </html>
  );
}
